"""empty message

Revision ID: 228a0620b0b6
Revises: 39a1f0e9608b
Create Date: 2015-09-02 20:17:33.049531

"""

# revision identifiers, used by Alembic.
revision = '228a0620b0b6'
down_revision = '39a1f0e9608b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('compute_time', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'compute_time')
    ### end Alembic commands ###
