"""empty message

Revision ID: 39a1f0e9608b
Revises: 104150ad9cb5
Create Date: 2015-08-31 22:16:22.054356

"""

# revision identifiers, used by Alembic.
revision = '39a1f0e9608b'
down_revision = '104150ad9cb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
